src/Entity/Ad.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;
// on utilise as pour renommer l'espace de nom
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
// se met non pas sur un champ mais sur l'entité entière pour vérifier qu'elle est unique

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *     fields={"title"},
 *     message="Une autre annonce possède déjà ce titre."
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractères.", maxMessage="Le titre doit faire moins de 255 catactères.")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="L'introduction doit faire plus de 20 caractères.")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="La description doit faire plus de 100 caractères.")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Image", mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    // assert valid vérifie que les images sont également valides (les asserts dans Image.php
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }


    /**
     * Permet d'initialiser le slug
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
     }

    /**
     * permet de récupérer le commentaire d'un auteur par rapport à une annonce
     * @param User $author
     * @return null|Comment
     */
     public function getCommentFromAuthor(User $author) {
        foreach($this->comments as $comment) {
            //on boucle sur tous les commentaires de l'annonce en questions pour voir si l'un deux a été donné par un certain user
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
     }

    /**
     * permet d'obtenir la moyenne des notes de l'annonce
     * @return float|int
     */
     public function getAvgRating() {
        // calculer la somme des notes (n veut réduire le tableau à une seule valeur)
         $sum = array_reduce($this->comments->toArray(), function($total, $comment) {
             return $total + $comment->getRating();
         }, 0);
             //$this->>comments est un array collection qu'on passe donc en array

         // faire la moyenne
         if(count($this->comments) > 0) return $sum / count($this->comments);

         return 0;
     }

    /**
     * Permet d'obtenir un tableau des jours non dispo pour ce bien.
     *
     * @return array Un tableau d'objets DateTime représentant les jours d'occupations
     */
     public function getNotAvailableDays() {
        $notAvailableDays = [];

        foreach($this->bookings as $booking) {
            //calculer les jours entre la date d'arrivée et la date de départ. Fonction range()  avec comme step le nb de secondes par jour
            $resultat = range(
                $booking->getStartDate()->getTimeStamp(),
                $booking->getEndDate()->getTimeStamp(),
                24 * 60 * 60
            );

            $days = array_map(function ($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);
            //fonction qui va me donner une image mirroir du tableau transformé. Il faut passer un fonction à array_map
            // Retroune nouvel objet de type datetime au format classique basée sur le timestamp reçu. Le fait sur le tableau $resultat. On va les ajouter au tableau des not availabledays

            $notAvailableDays = array_merge($notAvailableDays, $days);
        }

        return $notAvailableDays;
     }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Image;
use App\Form\AnnonceType;
use App\Repository\AdRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;


class AdController extends AbstractController
{
    /**
     * @Route("/ads", name="ads_index")
     */
    public function index(AdRepository $repo)
    {
        //$repo = $this->getDoctrine()->getRepository(Ad::class);
        //plus besoin car on a mis public function index(AdRepository $repo)   (injection de dépendance)

        $ads = $repo->findAll();

        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }

    /**
     * Permet de créer une annonce. On ajoute isGranted pour que seuls ceux connectés puissent ajouter une annonce.
     *
     * @Route("/ads/new", name="ads_create")
     * @IsGranted("ROLE_USER")
     * @return Response
     */
    public function create(Request $request, ObjectManager $manager)
    {
        // request correspond à la requête http, y compris dans le POST
        $ad = new Ad;

        $form = $this->createForm(AnnonceType::class, $ad);

        $form->handleRequest($request);
        // formulaire va analyser la requête et retrouver tous les champs, va les relier à notre variable ad et les places dans l'entité ad

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());
            // on dit que l'auteur est l'utilisateur connecté

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success', // correspons à la classe verte de bootstrap
                "L'annonce <strong>{$ad->getTitle()}</strong> a bien été créée."
            );


            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);
        }


        return $this->render('ad/new.html.twig', [
            'form' => $form->createView()  // va passer le formulaire dans twig
        ]);

    }

    /**
     * permet d'éditer une annonce. Securty permet de fare en sorte que seul le proprio peut modifier
     *
     * @Route("/ads/{slug}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user === ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier.")
     *
     * @return Response
     *
     */
    public function edit(Ad $ad, Request $request, ObjectManager $manager)
    {
        $form = $this->createForm(AnnonceType::class, $ad);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($ad->getImages() as $image) {
                $image->setAd($ad);
                $manager->persist($image);
            }

            $manager->persist($ad);
            $manager->flush();

            $this->addFlash(
                'success', // correspons à la classe verte de bootstrap
                "Les modification de l'annonce <strong>{$ad->getTitle()}</strong> ont bien été enregistrées."
            );


            return $this->redirectToRoute('ads_show', [
                'slug' => $ad->getSlug()
            ]);

        }

        return $this->render('ad/edit.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     * permet d'afficher une seule annonce
     *
     * @Route("/ads/{slug}", name="ads_show")
     * @return Response
     *
     */
    public function show(Ad $ad)
    {
        //$ad = $repo->findOneBySlug($slug);
        // on a retiré la ligne ci-dessus et ajouté Ad $ad dans les params (paramconverter) (et retiré le $slug)
        // avec findBy, on peut mettre le nom de n'importe quel champ de l'entité
        // findBy renvoie un tableau. findOneBy en renvoie un seul.

        return $this->render('ad/show.html.twig', [
            'ad' => $ad
        ]);
    }

    /**
     * @Route("/ads/{slug}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user == ad.getAuthor()", message="Vous n'avez pas le droit d'accéder à cette annonce.")
     *
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return Response
     *
     */
    public function delete(Ad $ad, ObjectManager $manager) {
        $manager->remove($ad);
        $manager->flush();

        $this->addFlash(
            'success',
            "L'annonce <strong> {$ad->getTitle()}</strong> a bien été supprimée."
        );

        return $this->redirectToRoute('ads_index');
    }

}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'slug': ad.slug}) %}
                {# on déclare une variable url pour factoriser #}
<div class="col-md-4">
    <div class="card bg-light mb-3">
        <div class="card-header text-center">
            {{ ad.rooms }} chambres, <strong>{{ ad.price | number_format(2, ',', ' ')}}&euro; / nuit</strong> <br>

            {% if ad.comments | length > 0 %}
                {% include 'partials/rating.html.twig' with {'rating': ad.avgRating}%}
            {% else %}
                <small>Pas encore noté</small>
            {% endif %}

        </div>
        <a href="{{ url }}">
            <img src="{{ ad.coverImage }}" alt="Image de l'appartement"
                 style="height: 200px; width: 100%; display: block">
        </a>

        <div class="card-body">
            <a href="{{ url }}">
                <h4 class="card-title">
                    {{ ad.title }}
                </h4>
            </a>
            <p class="card-text">
                {{ ad.introduction }}
            </p>
            <a href="{{ url }}" class="btn btn-primary float-right">En savoir plus</a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
                <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
                   onclick="return confirm(`Etes-vous sûr de vouloir supprimer l'annonce {{ ad.title }}?`)">Supprimer
                    l'annonce</a>
            {% endif %}
        </div>
    </div>
</div>

templates/ad/_collection.html.twig
{% block _annonce_images_widget %}
    {# ce bloc va permettre de définir l'affichage du champ ad_images #}
    {{ form_widget(form) }}
    {# ici form = ad_images #}

    <input type="hidden" id="widgets-counter" value="0">
    {# on crée un input caché avec une valeur de départ de 0 qui va compter le nombre d'entrées #}

    <div class="form-group">
        <button type="button" id="add-image" class="btn btn-primary">
            <i class="fas fa-plus"></i>
            Ajouter une image
        </button>
    </div>
{% endblock %}

{% block _annonce_images_entry_row %}
    {{ form_widget(form) }}
    {# du coup on n'appelle plus le label etc. On n'appelle que le widget. #}
{% endblock %}


{% block _annonce_images_entry_widget %}
    {# entry = élément de la collection #}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div class="col">
                        {{ form_widget(form.url) }}
                        {{ form_errors(form.url) }}
                        {# form représente ici une entry (qui, ici, sont des ImageType #}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                        {{ form_errors(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button button="" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edition d'une annonce{% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

    <div class="container">
        <h1>Editer l'annonce : {{ ad.title }}</h1>
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" class="btn btn-primary">Editer</button>
        {{ form_end(form) }}
    </div>
{% endblock %}



{% block javascripts %}
    <script src="{{ asset('build/js/ad.js') }}"></script>
{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces !{% endblock %}

{% block body %}
    <div class="container">
<h1 class="my-5">Voici les annonces de nos hôtes !</h1>

        <div class="row">
            {% for ad in ads %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} Création d'une annonce {% endblock %}

{% form_theme form 'ad/_collection.html.twig' %}
{# on met _self car le thème est défini dans ce fichier. Sinon on pourrait mettre l'url du fichier #}



{% block body %}

    <div class="container">
        <h1 class="my-5">Créer une nouvelle annonce</h1>

        {{ form_start(form) }}
        {# début du formulaire form #}

        {# {{ form_row(form) }} #}
        {# comprends label, widget, erros... #}

        {# {{ form_widget(form) }} #}
        {# permet plus de flexibilité car du coup on peut ajouter des choses au début ou à la fin #}
        {# form.title : on n'a que le champ title qui s'affiche avant le bouton mais le reste s'affiche après le bouton à cause du form(end)#}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Informations générales</h2>
                    <hr>
                    {{ form_row(form.title) }}
                    {{ form_row(form.slug) }}
                    {{ form_row(form.price) }}
                    {{ form_row(form.rooms) }}

                    {# permet d'afficher un champ avec son label, ses erreurs etc #}

                </div>
                <div class="alert alert-light">
                    <h2>Détails de l'annonce</h2>
                    <hr>
                    {{ form_row(form.introduction) }}
                    {{ form_row(form.content) }}
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2>Images de l'annonce</h2>
                    <hr>
                    {{ form_row(form.coverImage) }}
                    {{ form_row(form.images) }}
                </div>

            </div>

            
        </div>

        <div class="alert alert-success clearfix">
            <!-- clearfix répare les prbs de flottement -->
            <h2 class="alert-heading">Sauvegarder mon annonce</h2>
            <p>Vous êtes sur le point de créer votre annonce.</p>
            <button type="submit" class="btn btn-primary float-right">
                <i class="fas fa-check"></i> Créer la nouvelle annonce
            </button>
        </div>


        {{ form_end(form) }}
        {# il ajoute automatiquement un jeton de sécurité #}

        {# {{ form(form) }} #}
        {# remplace tout #}
    </div>

{% endblock %}

{# plutôt que de définir le thème soi-même, on va en prendre un dans la communauté #}

{% block javascripts %}
    <script src="{{ asset('build/js/ad.js') }}"></script>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ ad.title }}
{% endblock %}

{% block body %}

    <div class="ad-title" style="background-image: url({{ ad.coverImage }})">
        <div class="container">
            <h1>
                {{ ad.title }}
            </h1>
            <p>
                {{ ad.introduction }}
            </p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres </strong> pour <strong>{{ ad.price | number_format(2, ',', ' ') }}&euro;</strong> par nuit
            </p>
            <a href="{{ path('booking_create', {'slug': ad.slug}) }}" class="btn btn-primary">Réserver !</a>

            {% if app.user and app.user == ad.author %}
                <a href="{{ path('ads_edit', {'slug': ad.slug}) }}" class="btn btn-secondary">Modifier l'annonce</a>
                <a href="{{ path('ads_delete', {'slug': ad.slug}) }}" class="btn btn-danger"
                   onclick="return confirm(`Etes-vous sûr de vouloir supprimer l'annonce {{ ad.title }}?`)">Supprimer
                    l'annonce</a>
            {% endif %}
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ ad.content | raw }}
                <!-- raw pour afficher le texte snas les balises apparentes -->

                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            {# pour changer le nb d'indicateurs selon le nb d'images #}
                            <li data-target="#carouselExampleIndicators"
                                data-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active" {% endif %}></li>
                            {# loop.index0  va indiquer à quel index de la boucle on est #}
                        {% endfor %}
                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %} active {% endif %}">
                                {#on met une boucle loop pour vérifier si c'est la première image car seule la première image doit avorir la classe active #}
                                <img src="{{ image.url }}" class="d-block w-100" alt="...">
                                <div class="carousel-caption d-none d-md-block">
                                    <h5>{{ ad.title }}</h5>
                                    <p>{{ image.caption }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <hr>

                {% if ad.comments | length > 0 %}
                    <h2 class="mb-3">Commentaires de nos voyageurs :</h2>

                    <div class="alert alert-info">
                        <h4 class="alert-heading text-center">
                            <div class="row align-items-center">
                                <div class="col">
                                    Note globale donnée par nos voyageurs
                                </div>
                                <div class="col">
                                    {% include 'partials/rating.html.twig' with {'rating': ad.avgRating} %}
                                    <br>
                                    <small>(Calculée sur {{ ad.comments | length }} avis)</small>
                                </div>
                            </div>
                        </h4>
                    </div>

                    {% for comment in ad.comments %}
                        <div class="bg-light rounded mb-3 py-3 px-3">
                            <strong>{{ comment.author.firstName }}</strong> a dit :
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note donnée : </strong>
                            {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                            <!-- on peut passer les variables dont on a besoin dans l'inclusion -->
                        </div>
                    {% endfor %}


                {% else %}

                    <h2>Cette annonce n'a pas encore reçu de commentaire.</h2>

                {% endif %}

            </div>


            <div class="col">
                {% set a = ad.author %}
                <div class="row mb-3 align-items-center">
                    <div class="col-3">
                        <a href="{{ path('user_show', {'slug' : a.slug}) }}">
                            <img src="{{ a.picture }}" class="avatar avatar-medium" alt="Avatar de {{ a.fullName }}">
                        </a>
                    </div>
                    <div class="col">
                        <a href="{{ path('user_show', {'slug' : a.slug}) }}">
                            <h3>{{ a.fullName }}</h3>
                        </a>
                        <span class="badge badge-primary">{{ a.ads | length }} annonces</span>
                    </div>
                </div>{{ a.description | raw }}</div>
        </div>
    </div>


{% endblock %}